<P> <img src="https://i.ibb.co/gyNf19D/nhslogo.png" alt="nhslogo" border="0" width="100" align="right"><font size="6"><b> CS4132 Data Analytics</b> </font>

# Lab 2.4: NumPy Array

## (Section 2.5) Manipulating an Array

Complete the following questions and upload your `.ipynb` file to Coursemology.

Name the file in the following format:

`Lab<Num><YourName>.ipynb`

Note that for each question, you should shortlist at least 3 non-trivial test cases to show the correctness of your solution.

### Q1

Create a function named `border()` which will

<ul>
<li><span lang="EN-GB">take in an argument&nbsp;<em>n&nbsp;</em>denoting the size of a 2D array</span></li>
<li><span lang="EN-GB">create a 2D array of shape&nbsp;<em>n</em>&nbsp;by&nbsp;<em>n</em>&nbsp;with 1 on the border and 0 inside</span></li>
<li><span lang="EN-GB">finally return the array created.</span></li>
</ul>
<p>For example, if&nbsp;<em>n</em>&nbsp;is 5, the following array will be returned:</p>
<pre>[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]</pre>

In [13]:
#your solution
import numpy as np
def border(n):
    t = np.zeros((n,n))
    t[(0,-1),:]=1.
    t[:,(0,-1)]=1.
    return t

Show how you test the correctness of your code below:

In [14]:
border(5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
border(2)

array([[1., 1.],
       [1., 1.]])

In [16]:
border(7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### Q2

Create a function named `checkerBoard()` which will
<ul>
<li><span lang="EN-GB">take in an argument&nbsp;<em>n&nbsp;</em>denoting the size of a 2D array</span></li>
<li><span lang="EN-GB">create a 2D array of shape&nbsp;<em>n</em>&nbsp;by&nbsp;<em>n</em></span>&nbsp;with a checkerboard pattern.&nbsp;</li>
<li><span lang="EN-GB">finally return the array created.</span></li>
</ul>
<p>For example, if&nbsp;<em>n&nbsp;</em>is 8, the following array will be returned:</p>
<pre>[[0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0],<br /> [0, 1, 0, 1, 0, 1, 0, 1],<br /> [1, 0, 1, 0, 1, 0, 1, 0]]</pre>

In [25]:
#your solution
def checkerBoard(n):
    t = np.zeros((n,n))
    t[::2,::2]=1.
    t[1::2,1::2]=1.
    return t

Show how you test the correctness of your code below:

In [26]:
checkerBoard(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [27]:
checkerBoard(7)

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

In [28]:
checkerBoard(2)

array([[1., 0.],
       [0., 1.]])

### Q3

Create a function named `swap()` which will
<ul>
<li><span lang="EN-GB">take in 3 argument, <em>arr</em>,&nbsp;<em>a&nbsp;</em>and&nbsp;<em>b</em></span></li>
<li>it will then swap the contents of <span lang="EN-GB"><em>arr&nbsp;</em></span>in column <em>a</em> and column <em>b</em></li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, given arr:</p>
<pre>[[ 0, 1,  2,  3],<br /> [ 4, 5,  6,  7],<br /> [ 8, 9,  10, 11],<br /> [12, 13, 14, 15]]</pre>
<p>Calling swap(arr,0,2) results in:</p>
<pre>[[ 2, 1,  0,  3],<br /> [ 6, 5,  4,  7],<br /> [10, 9,  8,  11],<br /> [14, 13, 12, 15]]</pre>

In [32]:
#your solution
def swap(arr, a, b):
    arrc = arr.copy()
    arrc[:,a]=arr[:,b]
    arrc[:,b]=arr[:,a]
    return arrc

Show how you test the correctness of your code below:

In [33]:
swap(np.array([[ 0, 1,  2,  3],
 [ 4, 5,  6,  7],
 [ 8, 9,  10, 11],
 [12, 13, 14, 15]]), 0,2)

array([[ 2,  1,  0,  3],
       [ 6,  5,  4,  7],
       [10,  9,  8, 11],
       [14, 13, 12, 15]])

### Q4

Create a function named `slot()` which will
<ul>
<li><span lang="EN-GB">take in 3 arguments, a 3d array&nbsp;<em>arr</em>, integers&nbsp;<em>a&nbsp;</em>and&nbsp;<em>b</em></span></li>
<li>it will then copy the contents in sheet a and insert into position b</li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, given arr:</p>
<pre>[[[11, 12],
 [13, 14]],

 [[21, 22],
 [23, 23]]]</pre>
<p>Calling slot(arr,1,0) results in:</p>
<pre>[[[21, 22],
  [23, 23]],

  [[11, 12],
  [13, 14]],
  
  [[21, 22],
  [23, 23]]]</pre>

In [46]:
#your solution
def slot(arr, a, b):
    arrc = arr.copy()
    arrc = np.insert(arrc,b,arr[a],axis=0)
    return arrc

Show how you test the correctness of your code below:

In [47]:
slot(np.array([[[11, 12],
 [13, 14]],

 [[21, 22],
 [23, 23]]]),1,0)

array([[[21, 22],
        [23, 23]],

       [[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 23]]])

### Q5

Create a function named `create3d()` which will
<ul>
<li><span lang="EN-GB">take in a integers <i>n</i></span></li>
<li>it will then create a 3d array of <em>n</em> by <em>n</em> by <em>n</em> with random integer values of range [1,99]</li>
<li><span lang="EN-GB">finally return the updated array</span></li>
</ul>
<p>For example, calling create3d(2) may result in:</p>
<pre>[[[ 5, 82],
  [15, 30]],

  [[ 1, 36],
   [65, 74]]]</pre>
<p>Calling create3d(3) may result in:</p>
<pre>[[[97, 21, 49],
  [70, 11, 63],
  [41, 57, 93]],

 [[75, 66, 27],
  [12, 28, 17],
  [65, 67, 82]],

 [[67, 97, 60],
  [72, 36, 24],
  [26, 82, 26]]]</pre>

In [ ]:
#your solution


Show how you test the correctness of your code below:

### Q6

Create a function named `verticalStack()` which will
<ul>
<li>take in a 3d array from create3d() from question 5</li>
<li>it will then stack the sheets in the array from create3d() in reverse order, resulting in a 2d array.</li>
<li><span lang="EN-GB">finally return the 2d array</span></li>
</ul>
<p>For example, create3d(3) may result in:</p>
<pre>      [[[29, 32, 35],
        [89, 59, 77],
        [37, 87, 80]],

       [[75, 95, 39],
        [14, 79, 83],
        [67, 25, 31]],

       [[81, 61, 10],
        [35, 60,  3],
        [93, 17, 91]]]</pre>
<p>Calling verticalStack(create3d(3)) will result in:</p>
<pre>      [[81, 61, 10],
       [35, 60,  3],
       [93, 17, 91],
       [75, 95, 39],
       [14, 79, 83],
       [67, 25, 31],
       [29, 32, 35],
       [89, 59, 77],
       [37, 87, 80]]</pre>

In [ ]:
#your solution


Show how you test the correctness of your code below: