<P> <img src="https://i.ibb.co/gyNf19D/nhslogo.png" alt="nhslogo" border="0" width="100" align="right"><font size="6"><b> CS4132 Data Analytics</b> </font>

# Lab 2.3: NumPy Array

## (Section 2.4) Operations on NumPy

Complete the following questions and upload your `.ipynb` file to Coursemology.

Name the file in the following format:

`Lab<Num><YourName>.ipynb`

### Q1

Use the numpy array created below to answer the questions below.

In [1]:
import numpy as np
data = np.array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

Find the average value of the second column (to two decimal places).

In [9]:
round(np.mean(data, axis=0,dtype=np.float64)[1], 2)

214895.8

Find the average value of the first 5 rows of the third and fourth columns.

In [8]:
np.mean(data[:5, 2:4], axis = 1)

array([171295. , 371760.5, 252829. , 446974. , 187434. ])

Find the median value of the last column.

In [12]:
np.median(data[:, -1], axis=0)

237483.0

Find the sum of all values in the array.

In [13]:
np.sum(data)

23526182

Find the minimum value in the array.

In [14]:
np.min(data)

3975

Find the sum of the first and last column. Then multiply each element by 5.

In [17]:
(data[:,1] + data[:,-1])*[5]

array([2074885, 1094220, 1757050,  330505, 1675640, 3722285, 1814480,
       3518340, 2773130, 2732800, 2370705, 2102235, 2765700, 2430755,
       3311005, 2134540, 2660155, 2212495, 4015100,  326860])

Find the sum of all even rows.

In [21]:
np.sum(data[1::2,:])

11138928

### Q2

Using the concept of array broadcasting, create a 2d array for 5 by 5 multiplication table.

In [26]:
r1,r2 = np.array([1,2,3,4,5]), np.array([[x] for x in range(1,6)])
r1*r2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Q3

You are given 2 lists containing the weight (in kg) and height (in m) of 20 individuals.

Calculate their BMI and store it in a 1d array.

BMI Formula: weight (kg) / [height (m)]^2

In [27]:
weight = [57, 54, 21, 54, 42, 44, 26, 30, 34, 44, 31, 39, 44, 28, 40, 58, 40, 24, 47, 57]
height = [1.22, 1.63, 1.74, 1.65, 1.73, 1.79, 1.72, 1.31, 1.76, 1.01, 1.36, 1.17, 1.11, 1.  , 1.56, 1.12, 1.35, 1.05, 1.23, 1.09]

In [36]:
w, h = np.array(weight), np.array(height)
res = w/(h**2)
res

array([38.29615695, 20.32443826,  6.93618708, 19.83471074, 14.03321193,
       13.73240536,  8.78853434, 17.48149875, 10.97623967, 43.13302617,
       16.76038062, 28.49002849, 35.71138706, 28.        , 16.4365549 ,
       46.2372449 , 21.9478738 , 21.76870748, 31.06616432, 47.97575962])

### Q4

You are given a list containing temperature in celsius. 

Convert the data into fahrenheit and store it in a 1d array.

Formula: °F = (°C ×  9 / 5 ) + 32 

In [32]:
celsius = [39.5, 21.8, 34.5, 25.1, 16.4, 15.8, 26.7, 31.6, 15.6, 21.8, 13.7, 48.7, 13.8, 46.1, 25.3, 43.4, 35.2, 19.4, 18.6, 16.3, 20.8, 15.9, 42. , 14.9, 20.6, 18.9, 30. , 12.9, 44. , 49.6]

In [38]:
c = np.array(celsius)
d = c*9/5+32
d

array([103.1 ,  71.24,  94.1 ,  77.18,  61.52,  60.44,  80.06,  88.88,
        60.08,  71.24,  56.66, 119.66,  56.84, 114.98,  77.54, 110.12,
        95.36,  66.92,  65.48,  61.34,  69.44,  60.62, 107.6 ,  58.82,
        69.08,  66.02,  86.  ,  55.22, 111.2 , 121.28])

### Q5

The quiz scores of class A and class B is given in the 3d array below.

Each class has 20 students, and there are a total of 3 quizzes.

In [39]:
scores = np.array([[[91, 55, 84],
                    [69, 12, 70],
                    [84, 75, 33],
                    [21, 91,  2],
                    [12, 60, 40],
                    [42, 91, 51],
                    [26, 47, 85],
                    [ 8, 21, 73],
                    [85, 12, 22],
                    [ 2, 79, 73],
                    [57, 74, 20],
                    [23, 98, 82],
                    [23, 73, 33],
                    [58, 81, 71],
                    [66, 74, 12],
                    [85, 16, 68],
                    [44, 26,  5],
                    [15, 13, 32],
                    [86, 67,  1],
                    [66,  8, 34]],

                   [[40, 37, 15],
                    [53, 73, 64],
                    [73, 90, 10],
                    [95, 94, 32],
                    [46, 20, 44],
                    [12, 86, 24],
                    [17, 20, 15],
                    [87, 51,  5],
                    [63, 82,  2],
                    [66,  9, 29],
                    [59, 24, 32],
                    [43, 43, 65],
                    [62,  6, 86],
                    [92, 29,  7],
                    [47, 76, 15],
                    [46, 56, 70],
                    [74, 80, 50],
                    [42, 91, 14],
                    [92, 13, 17],
                    [76,  2, 54]]])

Find the average of each quiz for each class.

In [60]:
np.mean(scores, axis = 1)

array([[48.15, 53.65, 44.55],
       [59.25, 49.1 , 32.5 ]])

Find the average of quiz score of each student in class B.

In [48]:
np.mean(scores[1], axis=1)

array([30.66666667, 63.33333333, 57.66666667, 73.66666667, 36.66666667,
       40.66666667, 17.33333333, 47.66666667, 49.        , 34.66666667,
       38.33333333, 50.33333333, 51.33333333, 42.66666667, 46.        ,
       57.33333333, 68.        , 49.        , 40.66666667, 44.        ])

Find the max scorer for quiz 3 for the respective classes.

In [53]:
np.max(scores[:,:,2], axis=1)

array([85, 86])

Find the median score for quiz 2 for each class.

In [54]:
np.median(scores[:,:,1], axis=1)

array([63.5, 47. ])